apiVersion: apps/v1
kind: Deployment
metadata:
  name: javawebapp
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: javawebapp
  template:
    metadata:
      labels:
        app: javawebapp
    spec:
      containers:
        - name: javawebapp
          image: kotasaimuralidhar/java-web-app-docker:10
          ports:
            - containerPort: 8080
